# Generated by Django 5.1.2 on 2026-02-07 06:30

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0013_mastermaindate_date_en_mastermaindate_date_kg_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bachelorprogram',
            options={'verbose_name': 'бакалавр', 'verbose_name_plural': 'бакалавры'},
        ),
        migrations.RemoveField(
            model_name='bachelorprogram',
            name='CareerPerspectives_en',
        ),
        migrations.RemoveField(
            model_name='bachelorprogram',
            name='CareerPerspectives_kg',
        ),
        migrations.RemoveField(
            model_name='bachelorprogram',
            name='CareerPerspectives_ru',
        ),
        migrations.RemoveField(
            model_name='bachelorprogram',
            name='Offline',
        ),
        migrations.RemoveField(
            model_name='bachelorprogram',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='bachelorprogram',
            name='description_kg',
        ),
        migrations.RemoveField(
            model_name='bachelorprogram',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='bachelorprogram',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='bachelorprogram',
            name='emoji',
        ),
        migrations.RemoveField(
            model_name='bachelorprogram',
            name='mainDiscipline_en',
        ),
        migrations.RemoveField(
            model_name='bachelorprogram',
            name='mainDiscipline_kg',
        ),
        migrations.RemoveField(
            model_name='bachelorprogram',
            name='mainDiscipline_ru',
        ),
        migrations.RemoveField(
            model_name='bachelorprogram',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='bachelorprogram',
            name='name_kg',
        ),
        migrations.RemoveField(
            model_name='bachelorprogram',
            name='name_ru',
        ),
        migrations.AddField(
            model_name='bachelorprogram',
            name='pdf_en',
            field=models.FileField(default=1, upload_to='', verbose_name='pdf (en)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bachelorprogram',
            name='pdf_kg',
            field=models.FileField(default=1, upload_to='', verbose_name='pdf (kg)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bachelorprogram',
            name='pdf_ru',
            field=models.FileField(default=1, upload_to='', verbose_name='pdf (ru)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bachelorprogram',
            name='ruling_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, verbose_name='правила приема на английском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bachelorprogram',
            name='ruling_kg',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, verbose_name='правила приема на кыргызском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bachelorprogram',
            name='ruling_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, verbose_name='правила приема на русском'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BachelorFaculties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=255, verbose_name='название факультета на русском')),
                ('name_en', models.CharField(max_length=255, verbose_name='название факультета на английский')),
                ('name_kg', models.CharField(max_length=255, verbose_name='название факультета на кыргызский')),
                ('sports_ru', models.CharField(max_length=500, verbose_name='виды спортов на русском')),
                ('sports_kg', models.CharField(max_length=500, verbose_name='виды спортов на кыргызском')),
                ('sports_en', models.CharField(max_length=500, verbose_name='виды спортов на английском')),
                ('bachelor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.bachelorprogram')),
            ],
        ),
    ]
