# Generated by Django 5.1.2 on 2026-02-07 09:35

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0014_alter_bachelorprogram_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='инфо на русском')),
                ('text_kg', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='инфо на кыргызский')),
                ('text_en', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='инфо на английский')),
                ('file_name_ru', models.CharField(max_length=233, verbose_name='название pdf файла на русском ')),
                ('file_name_en', models.CharField(max_length=233, verbose_name='название pdf файла на английском ')),
                ('file_name_kg', models.CharField(max_length=233, verbose_name='название pdf файла на русском ')),
                ('pdf_ru', models.FileField(upload_to='', verbose_name='pdf (ru)')),
                ('pdf_kg', models.FileField(upload_to='', verbose_name='pdf (kg)')),
                ('pdf_en', models.FileField(upload_to='', verbose_name='pdf (en)')),
            ],
            options={
                'verbose_name': 'магистратура',
                'verbose_name_plural': 'магистратура',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='инфо на русском')),
                ('text_kg', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='инфо на кыргызский')),
                ('text_en', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='инфо на английский')),
                ('file_name_ru', models.CharField(max_length=233, verbose_name='название pdf файла на русском ')),
                ('file_name_en', models.CharField(max_length=233, verbose_name='название pdf файла на английском ')),
                ('file_name_kg', models.CharField(max_length=233, verbose_name='название pdf файла на русском ')),
                ('pdf_ru', models.FileField(upload_to='', verbose_name='pdf (ru)')),
                ('pdf_kg', models.FileField(upload_to='', verbose_name='pdf (kg)')),
                ('pdf_en', models.FileField(upload_to='', verbose_name='pdf (en)')),
            ],
            options={
                'verbose_name': 'магистратура',
                'verbose_name_plural': 'магистратура',
            },
        ),
        migrations.DeleteModel(
            name='DoctorAdmissionSteps',
        ),
        migrations.DeleteModel(
            name='DoctorPrograms',
        ),
        migrations.DeleteModel(
            name='DoctorSoonEvents',
        ),
        migrations.DeleteModel(
            name='DoctorStatistics',
        ),
        migrations.DeleteModel(
            name='MasterDocuments',
        ),
        migrations.DeleteModel(
            name='MasterMainDate',
        ),
        migrations.DeleteModel(
            name='MasterPrograms',
        ),
        migrations.DeleteModel(
            name='MasterRequirements',
        ),
        migrations.AlterField(
            model_name='bachelorfaculties',
            name='bachelor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='admission.bachelorprogram'),
        ),
    ]
