# Generated by Django 5.1.2 on 2026-02-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0015_doctorate_master_delete_doctoradmissionsteps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bachelorprogram',
            name='file_name_en',
            field=models.CharField(default=1, verbose_name='имя файла на английском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bachelorprogram',
            name='file_name_kg',
            field=models.CharField(default=1, verbose_name='имя файла на кыргызском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bachelorprogram',
            name='file_name_ru',
            field=models.CharField(default=1, verbose_name='имя файла на русском'),
            preserve_default=False,
        ),
    ]
