# Generated by Django 5.1.2 on 2026-02-09 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0016_bachelorprogram_file_name_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorate',
            options={'verbose_name': 'доктурантура', 'verbose_name_plural': 'доктурантура'},
        ),
    ]
