# Generated by Django 5.1.2 on 2026-02-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0017_alter_doctorate_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bachelorprogram',
            name='file_name_en',
            field=models.CharField(max_length=255, verbose_name='имя файла на английском'),
        ),
        migrations.AlterField(
            model_name='bachelorprogram',
            name='file_name_kg',
            field=models.CharField(max_length=255, verbose_name='имя файла на кыргызском'),
        ),
        migrations.AlterField(
            model_name='bachelorprogram',
            name='file_name_ru',
            field=models.CharField(max_length=255, verbose_name='имя файла на русском'),
        ),
    ]
