# Generated by Django 5.1.2 on 2026-01-19 10:55

import ckeditor_uploader.fields
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership_structure', '0002_document_leadership_organizationstructure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profsoyuz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание (RU)')),
                ('description_kg', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Описание (KG)')),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Описание (EN)')),
            ],
            options={
                'verbose_name': 'Профсоюз',
                'verbose_name_plural': 'Профсоюз',
            },
        ),
        migrations.DeleteModel(
            name='Commission',
        ),
        migrations.DeleteModel(
            name='TradeUnionBenefit',
        ),
        migrations.DeleteModel(
            name='TradeUnionEvent',
        ),
        migrations.DeleteModel(
            name='TradeUnionStats',
        ),
        migrations.AlterModelOptions(
            name='auditcommission',
            options={'verbose_name': 'Член  комиссии', 'verbose_name_plural': ' комиссия'},
        ),
        migrations.AlterModelOptions(
            name='boardoftrustees',
            options={'verbose_name': 'Член попечительского совета', 'verbose_name_plural': 'Попечительский совет'},
        ),
        migrations.RemoveField(
            model_name='auditcommission',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='auditcommission',
            name='achievements_en',
        ),
        migrations.RemoveField(
            model_name='auditcommission',
            name='achievements_kg',
        ),
        migrations.RemoveField(
            model_name='auditcommission',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='auditcommission',
            name='department',
        ),
        migrations.RemoveField(
            model_name='auditcommission',
            name='department_en',
        ),
        migrations.RemoveField(
            model_name='auditcommission',
            name='department_kg',
        ),
        migrations.RemoveField(
            model_name='auditcommission',
            name='email',
        ),
        migrations.RemoveField(
            model_name='auditcommission',
            name='image',
        ),
        migrations.RemoveField(
            model_name='auditcommission',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='auditcommission',
            name='name',
        ),
        migrations.RemoveField(
            model_name='auditcommission',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='auditcommission',
            name='name_kg',
        ),
        migrations.RemoveField(
            model_name='auditcommission',
            name='order',
        ),
        migrations.RemoveField(
            model_name='auditcommission',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='auditcommission',
            name='position',
        ),
        migrations.RemoveField(
            model_name='auditcommission',
            name='position_en',
        ),
        migrations.RemoveField(
            model_name='auditcommission',
            name='position_kg',
        ),
        migrations.RemoveField(
            model_name='auditcommission',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='boardoftrustees',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='boardoftrustees',
            name='achievements_en',
        ),
        migrations.RemoveField(
            model_name='boardoftrustees',
            name='achievements_kg',
        ),
        migrations.RemoveField(
            model_name='boardoftrustees',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='boardoftrustees',
            name='bio_en',
        ),
        migrations.RemoveField(
            model_name='boardoftrustees',
            name='bio_kg',
        ),
        migrations.RemoveField(
            model_name='boardoftrustees',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='boardoftrustees',
            name='email',
        ),
        migrations.RemoveField(
            model_name='boardoftrustees',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='boardoftrustees',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='boardoftrustees',
            name='order',
        ),
        migrations.RemoveField(
            model_name='boardoftrustees',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='boardoftrustees',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='auditcommission',
            name='text_en',
            field=models.CharField(default=1, max_length=200, verbose_name='Текст (EN)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditcommission',
            name='text_kg',
            field=models.CharField(default=1, max_length=200, verbose_name='Текст (KG)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditcommission',
            name='text_ru',
            field=models.CharField(default=1, max_length=200, verbose_name='Текст (RU)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boardoftrustees',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Фото'),
        ),
    ]
