# Generated by Django 5.1.2 on 2026-01-19 11:29

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leadership_structure', '0003_profsoyuz_delete_commission_delete_tradeunionbenefit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditcommission',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Член  комиссии', 'verbose_name_plural': ' комиссия'},
        ),
        migrations.AddField(
            model_name='auditcommission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now, verbose_name='Создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditcommission',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='auditcommission',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок отображения'),
        ),
        migrations.AddField(
            model_name='auditcommission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
