# Generated by Django 5.1.2 on 2026-01-21 05:55

import ckeditor_uploader.fields
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership_structure', '0004_alter_auditcommission_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadership',
            options={'verbose_name': 'Руководство академии', 'verbose_name_plural': 'Руководство академии'},
        ),
        migrations.RenameField(
            model_name='leadership',
            old_name='position_en',
            new_name='postion_en',
        ),
        migrations.RenameField(
            model_name='leadership',
            old_name='position_kg',
            new_name='postion_kg',
        ),
        migrations.RenameField(
            model_name='leadership',
            old_name='position',
            new_name='postion_ru',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='achievements_en',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='achievements_kg',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='department',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='department_en',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='department_kg',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='education',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='education_en',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='education_kg',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='email',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='image',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='leadership_type',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='leadership',
            name='bio_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, verbose_name='Биография (RU)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadership',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='bio_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Биография (EN)'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='bio_kg',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Биография (KG)'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Порядок отображения'),
        ),
    ]
