# Generated by Django 5.1.2 on 2026-01-21 06:05

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership_structure', '0005_alter_leadership_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadership',
            name='postion_en',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='postion_kg',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='postion_ru',
        ),
        migrations.AddField(
            model_name='leadership',
            name='position_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Должность (EN)'),
        ),
        migrations.AddField(
            model_name='leadership',
            name='position_kg',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Должность (KG)'),
        ),
        migrations.AddField(
            model_name='leadership',
            name='position_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Должность (RU)'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='bio_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Биография (EN)'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='bio_kg',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Биография (KG)'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='bio_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Биография (RU)'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ФИО (RU)'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ФИО (EN)'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='name_kg',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ФИО (KG)'),
        ),
    ]
