# Generated by Django 5.1.2 on 2026-01-21 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadership_structure', '0006_remove_leadership_postion_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadership',
            old_name='name',
            new_name='name_ru',
        ),
    ]
