# Generated by Django 5.1.2 on 2026-01-21 08:20

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadership_structure', '0007_rename_name_leadership_name_ru'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditcommission',
            options={'verbose_name': 'Член  комиссии', 'verbose_name_plural': ' комиссия'},
        ),
        migrations.AlterModelOptions(
            name='leadership',
            options={'verbose_name': 'Ректорат академии', 'verbose_name_plural': 'Ректорат академии'},
        ),
        migrations.RemoveField(
            model_name='auditcommission',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='auditcommission',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='auditcommission',
            name='order',
        ),
        migrations.RemoveField(
            model_name='auditcommission',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='auditcommission',
            name='text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=200, null=True, verbose_name='Текст (EN)'),
        ),
        migrations.AlterField(
            model_name='auditcommission',
            name='text_kg',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=200, null=True, verbose_name='Текст (KG)'),
        ),
        migrations.AlterField(
            model_name='auditcommission',
            name='text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=200, verbose_name='Текст (RU)'),
        ),
    ]
