# Generated by Django 5.1.2 on 2026-01-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership_structure', '0009_commission_delete_auditcommissionstatistics_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academiccouncil',
            options={'verbose_name': 'Член академического совета', 'verbose_name_plural': 'академический совет'},
        ),
        migrations.AlterModelOptions(
            name='administrativeunit',
            options={'verbose_name': 'Административные подразделения', 'verbose_name_plural': 'Административные подразделения'},
        ),
        migrations.AlterModelOptions(
            name='auditcommission',
            options={'verbose_name': 'Член ревизионной комиссии', 'verbose_name_plural': 'ревизионная комиссия'},
        ),
        migrations.AddField(
            model_name='administrativeunit',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название (EN)'),
        ),
        migrations.AddField(
            model_name='administrativeunit',
            name='name_kg',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название (KG)'),
        ),
        migrations.AddField(
            model_name='administrativeunit',
            name='name_ru',
            field=models.CharField(default=1, max_length=200, verbose_name='Название (RU)'),
            preserve_default=False,
        ),
    ]
