# Generated by Django 5.1.2 on 2026-02-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('about', 'About the Journal'), ('aims', 'Aims and Scope'), ('guidelines', 'Guidelines for Authors'), ('requirements', 'Author Requirements'), ('indexing', 'Indexing and Abstracting'), ('ethics', 'Publication Ethics'), ('contacts', 'Contact Information')], max_length=30, unique=True)),
                ('content_ru', models.TextField()),
                ('content_en', models.TextField()),
                ('content_kg', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
