# Generated by Django 6.0.2 on 2026-02-17 07:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalsection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='journalsection',
            name='content_en',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='journalsection',
            name='content_kg',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='journalsection',
            name='content_ru',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
