# Generated by Django 6.0.2 on 2026-02-17 08:02

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journalsection_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialBoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_ru', models.CharField(max_length=255)),
                ('full_name_en', models.CharField(max_length=255)),
                ('full_name_kg', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EditorialOfficeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_ru', models.CharField(max_length=255)),
                ('full_name_en', models.CharField(max_length=255)),
                ('full_name_kg', models.CharField(max_length=255)),
                ('position_ru', models.CharField(max_length=255)),
                ('position_en', models.CharField(max_length=255)),
                ('position_kg', models.CharField(max_length=255)),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='JournalArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('title_kg', models.CharField(max_length=255)),
                ('pdf_ru', models.FileField(blank=True, null=True, upload_to='journal/archive/', verbose_name='PDF (RU)')),
                ('pdf_en', models.FileField(blank=True, null=True, upload_to='journal/archive/', verbose_name='PDF (EN)')),
                ('pdf_kg', models.FileField(blank=True, null=True, upload_to='journal/archive/', verbose_name='PDF (KG)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='LatestIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('title_kg', models.CharField(max_length=255)),
                ('pdf_ru', models.FileField(blank=True, null=True, upload_to='journal/latest/', verbose_name='PDF (RU)')),
                ('pdf_en', models.FileField(blank=True, null=True, upload_to='journal/latest/', verbose_name='PDF (EN)')),
                ('pdf_kg', models.FileField(blank=True, null=True, upload_to='journal/latest/', verbose_name='PDF (KG)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
