# Generated by Django 5.1.2 on 2026-03-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_editorialboardmember_editorialofficemember_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('title_kg', models.CharField(max_length=255)),
                ('file_ru', models.FileField(blank=True, null=True, upload_to='editorial_board/', verbose_name='PDF файл (RU)')),
                ('file_en', models.FileField(blank=True, null=True, upload_to='editorial_board/', verbose_name='PDF файл (EN)')),
                ('file_kg', models.FileField(blank=True, null=True, upload_to='editorial_board/', verbose_name='PDF файл (KG)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Редколлегия',
                'verbose_name_plural': 'Редколлегия',
            },
        ),
        migrations.DeleteModel(
            name='EditorialBoardMember',
        ),
        migrations.DeleteModel(
            name='EditorialOfficeMember',
        ),
    ]
