# Generated by Django 6.0.2 on 2026-03-03 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_editorialboard_delete_editorialboardmember_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('title_kg', models.CharField(max_length=255)),
                ('file_ru', models.FileField(blank=True, null=True, upload_to='archive/ru/', verbose_name='PDF (RU)')),
                ('file_en', models.FileField(blank=True, null=True, upload_to='archive/en/', verbose_name='PDF (EN)')),
                ('file_kg', models.FileField(blank=True, null=True, upload_to='archive/kg/', verbose_name='PDF (KG)')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ArchiveYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.DeleteModel(
            name='JournalArchive',
        ),
        migrations.AddField(
            model_name='archiveitem',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='journal.archiveyear'),
        ),
    ]
