# Generated by Django 5.1.2 on 2026-03-04 09:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_archiveitem_archiveyear_delete_journalarchive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialOfficeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=255, verbose_name='ФИО (RU)')),
                ('name_en', models.CharField(max_length=255, verbose_name='ФИО (EN)')),
                ('name_kg', models.CharField(max_length=255, verbose_name='ФИО (KG)')),
                ('position_ru', models.CharField(max_length=255, verbose_name='Должность (RU)')),
                ('position_en', models.CharField(max_length=255, verbose_name='Должность (EN)')),
                ('position_kg', models.CharField(max_length=255, verbose_name='Должность (KG)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='journal/editorial_office/', verbose_name='Фото')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Описание (RU)')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Описание (EN)')),
                ('description_kg', ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Описание (KG)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Член редакции',
                'verbose_name_plural': 'Редакция журнала',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
