# Generated by Django 6.0.3 on 2026-03-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_editorialofficemember'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalsection',
            name='pdf_en',
            field=models.FileField(blank=True, null=True, upload_to='journal/sections/', verbose_name='PDF (EN)'),
        ),
        migrations.AddField(
            model_name='journalsection',
            name='pdf_kg',
            field=models.FileField(blank=True, null=True, upload_to='journal/sections/', verbose_name='PDF (KG)'),
        ),
        migrations.AddField(
            model_name='journalsection',
            name='pdf_ru',
            field=models.FileField(blank=True, null=True, upload_to='journal/sections/', verbose_name='PDF (RU)'),
        ),
    ]
