# Generated by Django 5.1.2 on 2026-03-05 08:11

import journal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_journalsection_pdf_en_journalsection_pdf_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveitem',
            name='file_en',
            field=models.FileField(blank=True, null=True, upload_to='archive/en/', validators=[journal.models.validate_file_size_50mb], verbose_name='PDF (EN)'),
        ),
        migrations.AlterField(
            model_name='archiveitem',
            name='file_kg',
            field=models.FileField(blank=True, null=True, upload_to='archive/kg/', validators=[journal.models.validate_file_size_50mb], verbose_name='PDF (KG)'),
        ),
        migrations.AlterField(
            model_name='archiveitem',
            name='file_ru',
            field=models.FileField(blank=True, null=True, upload_to='archive/ru/', validators=[journal.models.validate_file_size_50mb], verbose_name='PDF (RU)'),
        ),
        migrations.AlterField(
            model_name='editorialboard',
            name='file_en',
            field=models.FileField(blank=True, null=True, upload_to='editorial_board/', validators=[journal.models.validate_file_size_50mb], verbose_name='PDF файл (EN)'),
        ),
        migrations.AlterField(
            model_name='editorialboard',
            name='file_kg',
            field=models.FileField(blank=True, null=True, upload_to='editorial_board/', validators=[journal.models.validate_file_size_50mb], verbose_name='PDF файл (KG)'),
        ),
        migrations.AlterField(
            model_name='editorialboard',
            name='file_ru',
            field=models.FileField(blank=True, null=True, upload_to='editorial_board/', validators=[journal.models.validate_file_size_50mb], verbose_name='PDF файл (RU)'),
        ),
        migrations.AlterField(
            model_name='journalsection',
            name='pdf_en',
            field=models.FileField(blank=True, null=True, upload_to='journal/sections/', validators=[journal.models.validate_file_size_50mb], verbose_name='PDF (EN)'),
        ),
        migrations.AlterField(
            model_name='journalsection',
            name='pdf_kg',
            field=models.FileField(blank=True, null=True, upload_to='journal/sections/', validators=[journal.models.validate_file_size_50mb], verbose_name='PDF (KG)'),
        ),
        migrations.AlterField(
            model_name='journalsection',
            name='pdf_ru',
            field=models.FileField(blank=True, null=True, upload_to='journal/sections/', validators=[journal.models.validate_file_size_50mb], verbose_name='PDF (RU)'),
        ),
        migrations.AlterField(
            model_name='latestissue',
            name='pdf_en',
            field=models.FileField(blank=True, null=True, upload_to='journal/latest/', validators=[journal.models.validate_file_size_50mb], verbose_name='PDF (EN)'),
        ),
        migrations.AlterField(
            model_name='latestissue',
            name='pdf_kg',
            field=models.FileField(blank=True, null=True, upload_to='journal/latest/', validators=[journal.models.validate_file_size_50mb], verbose_name='PDF (KG)'),
        ),
        migrations.AlterField(
            model_name='latestissue',
            name='pdf_ru',
            field=models.FileField(blank=True, null=True, upload_to='journal/latest/', validators=[journal.models.validate_file_size_50mb], verbose_name='PDF (RU)'),
        ),
    ]
