# Generated by Django 5.1.2 on 2026-03-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_alter_archiveitem_file_en_alter_archiveitem_file_kg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Название (RU)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Название (EN)')),
                ('title_kg', models.CharField(max_length=255, verbose_name='Название (KG)')),
                ('pdf_ru', models.FileField(blank=True, null=True, upload_to='Journal/regulations/', verbose_name='PDF (RU)')),
                ('pdf_en', models.FileField(blank=True, null=True, upload_to='Journal/regulations/', verbose_name='PDF (EN)')),
                ('pdf_kg', models.FileField(blank=True, null=True, upload_to='Journal/regulations/', verbose_name='PDF (KG)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Положение',
                'verbose_name_plural': 'Положения',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ThemeRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Название темы (RU)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Название темы (EN)')),
                ('title_kg', models.CharField(max_length=255, verbose_name='Название темы (KG)')),
                ('pdf_ru', models.FileField(blank=True, null=True, upload_to='Journal/themes/', verbose_name='PDF (RU)')),
                ('pdf_en', models.FileField(blank=True, null=True, upload_to='Journal/themes/', verbose_name='PDF (EN)')),
                ('pdf_kg', models.FileField(blank=True, null=True, upload_to='Journal/themes/', verbose_name='PDF (KG)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Реестр тем',
                'verbose_name_plural': 'Реестр тем',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
