# Generated by Django 5.1.2 on 2026-01-22 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('military_faculty', '0010_alter_gallerycard_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='military_faculty.tabcategory', verbose_name='Таб'),
        ),
    ]
