# Generated by Django 5.1.2 on 2026-01-19 09:59

import ckeditor_uploader.fields
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0011_rename_description_ky_aboutphotos_description_kg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Главное изображение')),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст истории(русский)')),
                ('text_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст истории(английский)')),
                ('text_kg', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст истории(кыргызский)')),
            ],
            options={
                'verbose_name': 'История академии',
                'verbose_name_plural': 'Истории академии',
            },
        ),
        migrations.DeleteModel(
            name='HistoryStep',
        ),
        migrations.DeleteModel(
            name='ImportantDates',
        ),
    ]
