# Generated by Django 5.1.2 on 2026-01-19 10:55

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0012_history_delete_historystep_delete_importantdates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accreditation',
            name='accreditation_type',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='accreditation',
            options={'verbose_name': 'Аккредитация', 'verbose_name_plural': 'Аккредитации'},
        ),
        migrations.RemoveField(
            model_name='accreditation',
            name='certificate_number',
        ),
        migrations.RemoveField(
            model_name='accreditation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='accreditation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='accreditation',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='accreditation',
            name='order',
        ),
        migrations.RemoveField(
            model_name='accreditation',
            name='organization_en',
        ),
        migrations.RemoveField(
            model_name='accreditation',
            name='organization_kg',
        ),
        migrations.RemoveField(
            model_name='accreditation',
            name='organization_ru',
        ),
        migrations.RemoveField(
            model_name='accreditation',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='accreditation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='accreditation',
            name='validity_en',
        ),
        migrations.RemoveField(
            model_name='accreditation',
            name='validity_kg',
        ),
        migrations.RemoveField(
            model_name='accreditation',
            name='validity_ru',
        ),
        migrations.AddField(
            model_name='accreditation',
            name='name_en',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accreditation',
            name='name_kg',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accreditation',
            name='name_ru',
            field=models.CharField(default=11, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accreditation',
            name='pdf_en',
            field=models.FileField(blank=True, null=True, upload_to='accreditation_pdfs/', verbose_name='PDF файл для аккредитации(английский)'),
        ),
        migrations.AddField(
            model_name='accreditation',
            name='pdf_kg',
            field=models.FileField(blank=True, null=True, upload_to='accreditation_pdfs/', verbose_name='PDF файл для аккредитации(кыргызский)'),
        ),
        migrations.AddField(
            model_name='accreditation',
            name='pdf_ru',
            field=models.FileField(blank=True, null=True, upload_to='accreditation_pdfs/', verbose_name='PDF файл для аккредитации(русский)'),
        ),
        migrations.AddField(
            model_name='mission',
            name='pdf_en',
            field=models.FileField(blank=True, null=True, upload_to='mission_pdfs/', verbose_name='PDF файл для миссии(английский)'),
        ),
        migrations.AddField(
            model_name='mission',
            name='pdf_kg',
            field=models.FileField(blank=True, null=True, upload_to='mission_pdfs/', verbose_name='PDF файл для миссии(кыргызский)'),
        ),
        migrations.AddField(
            model_name='mission',
            name='pdf_ru',
            field=models.FileField(blank=True, null=True, upload_to='mission_pdfs/', verbose_name='PDF файл для миссии(русский)'),
        ),
        migrations.AlterField(
            model_name='accreditation',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание на английском'),
        ),
        migrations.AlterField(
            model_name='accreditation',
            name='description_kg',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание на кыргызском'),
        ),
        migrations.AlterField(
            model_name='accreditation',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание на русском'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание на английском'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='description_kg',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание на кыргызском'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание на русском'),
        ),
        migrations.DeleteModel(
            name='AccreditationType',
        ),
        migrations.DeleteModel(
            name='MissionCategory',
        ),
    ]
