# Generated by Django 5.1.2 on 2026-02-07 09:35

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название программы (RU)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Название программы (EN)')),
                ('name_kg', models.CharField(max_length=200, verbose_name='Название программы (KG)')),
                ('description_ru', models.TextField(verbose_name='Описание программы (RU)')),
                ('description_en', models.TextField(verbose_name='Описание программы (EN)')),
                ('description_kg', models.TextField(verbose_name='Описание программы (KG)')),
                ('eligibility_criteria_ru', models.TextField(verbose_name='Критерии отбора (RU)')),
                ('eligibility_criteria_en', models.TextField(verbose_name='Критерии отбора (EN)')),
                ('eligibility_criteria_kg', models.TextField(verbose_name='Критерии отбора (KG)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма стипендии')),
                ('currency', models.CharField(default='KGS', max_length=10, verbose_name='Валюта')),
                ('application_deadline', models.DateField(verbose_name='Дедлайн подачи заявок')),
                ('application_link', models.URLField(blank=True, null=True, verbose_name='Ссылка для подачи заявки')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Контактный email')),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Контактный телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Scholarship Program',
                'verbose_name_plural': 'Scholarship Programs',
                'ordering': ['name_ru'],
            },
        ),
        migrations.CreateModel(
            name='StudentExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='фото')),
                ('name_ru', models.CharField(max_length=255, verbose_name='название программы на русском')),
                ('name_en', models.CharField(max_length=255, verbose_name='название программы на английском')),
                ('name_kg', models.CharField(max_length=255, verbose_name='название программы на кыргызском')),
                ('desc_ru', models.CharField(max_length=1005, verbose_name='описание программы на русском')),
                ('desc_en', models.CharField(max_length=1005, verbose_name='описание программы на английском')),
                ('desc_kg', models.CharField(max_length=1005, verbose_name='описание программы на кыргызском')),
            ],
            options={
                'verbose_name': 'студентеческий обмен',
            },
        ),
        migrations.CreateModel(
            name='StudentInstractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_ru', models.FileField(upload_to='', verbose_name='pdf(ru)')),
                ('pdf_en', models.FileField(upload_to='', verbose_name='pdf(en)')),
                ('pdf_kg', models.FileField(upload_to='', verbose_name='pdf(kg)')),
            ],
            options={
                'verbose_name': 'инструкции',
            },
        ),
        migrations.CreateModel(
            name='StudentsCouncil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='текст на русском')),
                ('text_en', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='текст на английском')),
                ('text_kg', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='текст на кыргызском')),
            ],
            options={
                'verbose_name': 'студентеческий совет',
            },
        ),
        migrations.CreateModel(
            name='StudentSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='текст на русском')),
                ('text_en', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='текст на английском')),
                ('text_kg', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='текст на кыргызском')),
            ],
            options={
                'verbose_name': 'поддержка студентов',
            },
        ),
        migrations.CreateModel(
            name='ScholarshipRequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название документа (RU)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Название документа (EN)')),
                ('name_kg', models.CharField(max_length=200, verbose_name='Название документа (KG)')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание документа (RU)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание документа (EN)')),
                ('description_kg', models.TextField(blank=True, null=True, verbose_name='Описание документа (KG)')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательный')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='students.scholarshipprogram', verbose_name='Стипендиальная программа')),
            ],
            options={
                'verbose_name': 'Required Document',
                'verbose_name_plural': 'Required Documents',
                'ordering': ['scholarship', 'order'],
            },
        ),
    ]
