# Generated by Django 5.1.2 on 2026-02-09 06:38

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinstractions',
            name='file_name_en',
            field=models.CharField(default=1, max_length=233, verbose_name='название pdf файла на английском '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentinstractions',
            name='file_name_kg',
            field=models.CharField(default=1, max_length=233, verbose_name='название pdf файла на русском '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentinstractions',
            name='file_name_ru',
            field=models.CharField(default=1, max_length=233, verbose_name='название pdf файла на русском '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentexchange',
            name='desc_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=1005, verbose_name='описание программы на английском'),
        ),
        migrations.AlterField(
            model_name='studentexchange',
            name='desc_kg',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=1005, verbose_name='описание программы на кыргызском'),
        ),
        migrations.AlterField(
            model_name='studentexchange',
            name='desc_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=1005, verbose_name='описание программы на русском'),
        ),
    ]
