# Generated by Django 6.0.2 on 2026-02-12 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0018_remove_sportsection_coach_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructureobject',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infra_objects', to='sports.infrastructurecategory', verbose_name='Категория'),
        ),
    ]
