# Generated by Django 5.1.2 on 2026-02-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Название (RU)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Название (EN)')),
                ('title_kg', models.CharField(max_length=255, verbose_name='Название (KG)')),
                ('file_ru', models.FileField(blank=True, null=True, upload_to='administrative_structure/', verbose_name='PDF файл (RU)')),
                ('file_en', models.FileField(blank=True, null=True, upload_to='administrative_structure/', verbose_name='PDF файл (EN)')),
                ('file_kg', models.FileField(blank=True, null=True, upload_to='administrative_structure/', verbose_name='PDF файл (KG)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Административная структура',
                'verbose_name_plural': 'Административные структуры',
            },
        ),
    ]
