# Generated by Django 5.1.2 on 2026-01-22 12:11

import ckeditor_uploader.fields
import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=300, verbose_name='Название (Русский)')),
                ('name_kg', models.CharField(max_length=300, verbose_name='Название (Кыргызча)')),
                ('name_en', models.CharField(max_length=300, verbose_name='Название (English)')),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('description_kg', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедры',
                'db_table': 'college_department',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Фото')),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='Заголовок (Русский)')),
                ('title_kg', models.CharField(blank=True, max_length=200, verbose_name='Заголовок (Кыргызча)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Заголовок (English)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (Русский)')),
                ('description_kg', models.TextField(blank=True, verbose_name='Описание (Кыргызча)')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (English)')),
            ],
            options={
                'verbose_name': 'Карточка галереи',
                'verbose_name_plural': 'Карточки галереи',
                'db_table': 'college_gallerycard',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TabCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Ключ')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Заголовок (Русский)')),
                ('title_kg', models.CharField(max_length=200, verbose_name='Заголовок (Кыргызча)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Заголовок (English)')),
                ('icon', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Иконка')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Категория/Таб',
                'verbose_name_plural': 'Категории/Табы',
                'db_table': 'college_tabcategory',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Имя (Русский)')),
                ('name_kg', models.CharField(max_length=200, verbose_name='Имя (Кыргызча)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Имя (English)')),
                ('position_ru', models.CharField(max_length=200, verbose_name='Должность (Русский)')),
                ('position_kg', models.CharField(max_length=200, verbose_name='Должность (Кыргызча)')),
                ('position_en', models.CharField(max_length=200, verbose_name='Должность (English)')),
                ('resume', models.FileField(blank=True, null=True, upload_to='', verbose_name='Резюме (PDF)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='college.department', verbose_name='Кафедра')),
            ],
            options={
                'verbose_name': 'Сотрудник кафедры',
                'verbose_name_plural': 'Сотрудники кафедры',
                'db_table': 'college_departmentstaff',
                'ordering': ['department', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=300, verbose_name='Название (Русский)')),
                ('title_kg', models.CharField(max_length=300, verbose_name='Название (Кыргызча)')),
                ('title_en', models.CharField(max_length=300, verbose_name='Название (English)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (Русский)')),
                ('description_kg', models.TextField(blank=True, verbose_name='Описание (Кыргызча)')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (English)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tab', models.ForeignKey(limit_choices_to={'key': 'specializations'}, on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='college.tabcategory', verbose_name='Таб')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
                'db_table': 'college_specialization',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Фото')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Имя (Русский)')),
                ('name_kg', models.CharField(max_length=200, verbose_name='Имя (Кыргызча)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Имя (English)')),
                ('role_ru', models.CharField(max_length=200, verbose_name='Роль (Русский)')),
                ('role_kg', models.CharField(max_length=200, verbose_name='Роль (Кыргызча)')),
                ('role_en', models.CharField(max_length=200, verbose_name='Роль (English)')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('resume', models.FileField(blank=True, null=True, upload_to='college/management/resumes/', verbose_name='Резюме (PDF)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tab', models.ForeignKey(limit_choices_to={'key': 'management'}, on_delete=django.db.models.deletion.CASCADE, related_name='management', to='college.tabcategory', verbose_name='Таб')),
            ],
            options={
                'verbose_name': 'Руководство',
                'verbose_name_plural': 'Руководство',
                'db_table': 'college_management',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='tab',
            field=models.ForeignKey(limit_choices_to={'key': 'departments'}, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='college.tabcategory', verbose_name='Таб'),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Заголовок (Русский)')),
                ('title_kg', models.CharField(max_length=200, verbose_name='Заголовок (Кыргызча)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Заголовок (English)')),
                ('description_ru', models.TextField(verbose_name='Описание (Русский)')),
                ('description_kg', models.TextField(verbose_name='Описание (Кыргызча)')),
                ('description_en', models.TextField(verbose_name='Описание (English)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='college.tabcategory', verbose_name='Таб')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
                'db_table': 'college_card',
                'ordering': ['tab', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AboutCollege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст (Русский)')),
                ('text_kg', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст (Кыргызча)')),
                ('text_en', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст (English)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tab', models.ForeignKey(limit_choices_to={'key': 'about_college'}, on_delete=django.db.models.deletion.CASCADE, related_name='about_college', to='college.tabcategory', verbose_name='Таб')),
            ],
            options={
                'verbose_name': 'О колледже',
                'verbose_name_plural': 'О колледже',
                'db_table': 'college_aboutcollege',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Картинка')),
                ('event_ru', models.TextField(verbose_name='Событие (Русский)')),
                ('event_kg', models.TextField(verbose_name='Событие (Кыргызча)')),
                ('event_en', models.TextField(verbose_name='Событие (English)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tab', models.ForeignKey(limit_choices_to={'key': 'history'}, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='college.tabcategory', verbose_name='Таб')),
            ],
            options={
                'verbose_name': 'Событие истории',
                'verbose_name_plural': 'События истории',
                'db_table': 'college_timelineevent',
                'ordering': ['order'],
            },
        ),
    ]
