# Generated by Django 5.1.2 on 2026-01-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=300, verbose_name='Название (Русский)')),
                ('title_kg', models.CharField(max_length=300, verbose_name='Название (Кыргызча)')),
                ('title_en', models.CharField(max_length=300, verbose_name='Название (English)')),
                ('pdf_ru', models.FileField(blank=True, null=True, upload_to='college/mission_strategy/pdfs/', verbose_name='PDF файл (Русский)')),
                ('pdf_kg', models.FileField(blank=True, null=True, upload_to='college/mission_strategy/pdfs/', verbose_name='PDF файл (Кыргызча)')),
                ('pdf_en', models.FileField(blank=True, null=True, upload_to='college/mission_strategy/pdfs/', verbose_name='PDF файл (English)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Миссия и стратегия',
                'verbose_name_plural': 'Миссии и стратегии',
                'db_table': 'college_missionstrategy',
                'ordering': ['order'],
            },
        ),
    ]
