# Generated by Django 5.1.2 on 2026-01-22 12:23

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_missionstrategy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Имя (Русский)')),
                ('name_kg', models.CharField(max_length=200, verbose_name='Имя (Кыргызча)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Имя (English)')),
                ('subject_ru', models.CharField(max_length=200, verbose_name='Предмет/Специальность (Русский)')),
                ('subject_kg', models.CharField(max_length=200, verbose_name='Предмет/Специальность (Кыргызча)')),
                ('subject_en', models.CharField(max_length=200, verbose_name='Предмет/Специальность (English)')),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Фото')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('resume', models.FileField(blank=True, null=True, upload_to='college/teachers/resumes/', verbose_name='Резюме (PDF)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'db_table': 'college_teacher',
                'ordering': ['order'],
            },
        ),
    ]
