# Generated by Django 5.1.2 on 2026-01-22 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_teacher'),
    ]

    operations = [
    ]
