# Generated by Django 5.1.2 on 2026-01-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0014_rename_pdf_vestnikrelease_pdf_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vestnikrelease',
            name='pdf_en',
            field=models.FileField(blank=True, upload_to='vestnik/releases/', verbose_name='PDF File (English)'),
        ),
        migrations.AlterField(
            model_name='vestnikrelease',
            name='pdf_kg',
            field=models.FileField(blank=True, upload_to='vestnik/releases/', verbose_name='PDF File (Kyrgyz)'),
        ),
        migrations.AlterField(
            model_name='vestnikrelease',
            name='pdf_ru',
            field=models.FileField(blank=True, upload_to='vestnik/releases/', verbose_name='PDF File (Russian)'),
        ),
    ]
