# Generated by Django 5.1.2 on 2026-02-18 10:15

import science.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0015_alter_vestnikrelease_pdf_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('title_kg', models.CharField(max_length=255)),
                ('authors_ru', models.CharField(max_length=255)),
                ('authors_en', models.CharField(max_length=255)),
                ('authors_kg', models.CharField(max_length=255)),
                ('file_ru', models.FileField(blank=True, null=True, upload_to='scientific_publications/', validators=[science.validators.validate_pdf], verbose_name='PDF (RU)')),
                ('file_en', models.FileField(blank=True, null=True, upload_to='scientific_publications/', validators=[science.validators.validate_pdf], verbose_name='PDF (EN)')),
                ('file_kg', models.FileField(blank=True, null=True, upload_to='scientific_publications/', validators=[science.validators.validate_pdf], verbose_name='PDF (KG)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scientific Publication',
                'verbose_name_plural': 'Scientific Publications',
                'ordering': ['-created_at'],
            },
        ),
    ]
