# Generated by Django 5.1.2 on 2026-02-07 05:57

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_collegedepartmentinfo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='информация(Русский)')),
                ('info_kg', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='информация(кыргызский)')),
                ('info_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='информация(английском)')),
                ('study_plan', models.URLField(blank=True, null=True, verbose_name='план обучения')),
                ('disciplines', models.URLField(blank=True, null=True, verbose_name='дисциплины')),
            ],
            options={
                'verbose_name': 'Магистратура',
                'verbose_name_plural': 'Магистратура',
            },
        ),
        migrations.CreateModel(
            name='Phd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='информация(Русский)')),
                ('info_kg', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='информация(кыргызский)')),
                ('info_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='информация(английском)')),
                ('study_plan', models.URLField(blank=True, null=True, verbose_name='план обучения')),
                ('disciplines', models.URLField(blank=True, null=True, verbose_name='дисциплины')),
            ],
            options={
                'verbose_name': 'Доктурантура',
                'verbose_name_plural': 'Доктурантура',
            },
        ),
        migrations.RemoveField(
            model_name='mastermanagement',
            name='department',
        ),
        migrations.CreateModel(
            name='MasterStuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio_kg', models.CharField(max_length=255, verbose_name='фио на кыргызском')),
                ('fio_ru', models.CharField(max_length=255, verbose_name='фио на русском')),
                ('fio_en', models.CharField(max_length=255, verbose_name='фио на английском')),
                ('pos_en', models.CharField(max_length=255, verbose_name='должность на английском')),
                ('pos_kg', models.CharField(max_length=255, verbose_name='должность на кыргызском')),
                ('pos_ru', models.CharField(max_length=255, verbose_name='должность на русском')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.master', verbose_name='магистр')),
            ],
            options={
                'verbose_name': 'сотрудник магистра',
                'verbose_name_plural': 'сотрудники магистра',
            },
        ),
        migrations.CreateModel(
            name='PhdStuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio_kg', models.CharField(max_length=255, verbose_name='фио на кыргызском')),
                ('fio_ru', models.CharField(max_length=255, verbose_name='фио на русском')),
                ('fio_en', models.CharField(max_length=255, verbose_name='фио на английском')),
                ('pos_en', models.CharField(max_length=255, verbose_name='должность на английском')),
                ('pos_kg', models.CharField(max_length=255, verbose_name='должность на кыргызском')),
                ('pos_ru', models.CharField(max_length=255, verbose_name='должность на русском')),
                ('Phd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.phd', verbose_name='магистр')),
            ],
            options={
                'verbose_name': 'сотрудник доктурантуры',
                'verbose_name_plural': 'сотрудники доктурантуры',
            },
        ),
        migrations.DeleteModel(
            name='MasterDepartmentInfo',
        ),
        migrations.DeleteModel(
            name='MasterManagement',
        ),
        migrations.DeleteModel(
            name='MasterTabCategory',
        ),
    ]
