# Generated by Django 5.1.2 on 2026-02-13 12:10

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True, verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Год вестника',
                'verbose_name_plural': 'Годы вестника',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='BulletinIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.PositiveIntegerField(verbose_name='Номер выпуска')),
                ('description_ru', ckeditor.fields.RichTextField(verbose_name='Описание (Русский)')),
                ('description_en', ckeditor.fields.RichTextField(verbose_name='Описание (English)')),
                ('description_kg', ckeditor.fields.RichTextField(verbose_name='Описание (Кыргызча)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='bulletin.bulletinyear', verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Выпуск вестника',
                'verbose_name_plural': 'Выпуски вестника',
                'ordering': ['issue_number'],
                'unique_together': {('year', 'issue_number')},
            },
        ),
    ]
