# Generated by Django 5.1.2 on 2026-02-12 04:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_ru', models.CharField(max_length=255, verbose_name='ФИО (рус)')),
                ('full_name_en', models.CharField(blank=True, max_length=255, verbose_name='Full Name (en)')),
                ('full_name_kg', models.CharField(blank=True, max_length=255, verbose_name='Аты-жөнү (кырг)')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание достижения (рус)')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, verbose_name='Achievement Description (en)')),
                ('description_kg', ckeditor.fields.RichTextField(blank=True, verbose_name='Жетишкендик сүрөттөмөсү (кырг)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='sport_achievements/photos/', verbose_name='Фото спортсмена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Спортивное достижение',
                'verbose_name_plural': 'Спортивные достижения',
                'ordering': ['-created_at'],
            },
        ),
    ]
