# Generated by Django 5.1.2 on 2026-02-12 04:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_ru', models.CharField(max_length=255, verbose_name='ФИО (рус)')),
                ('full_name_en', models.CharField(blank=True, max_length=255, verbose_name='Full Name (en)')),
                ('full_name_kg', models.CharField(blank=True, max_length=255, verbose_name='Аты-жөнү (кырг)')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание (рус)')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, verbose_name='Description (en)')),
                ('description_kg', ckeditor.fields.RichTextField(blank=True, verbose_name='Сүрөттөмө (кырг)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='graduates/photos/', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Выпускник',
                'verbose_name_plural': 'Выпускники',
                'ordering': ['-created_at'],
            },
        ),
    ]
