# Generated by Django 6.0.2 on 2026-02-12 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduate',
            name='photo',
        ),
    ]
